### ISSUE TITLE
Unable to render textures on models

### ISSUE THREAD

**Issue by Nv7-GitHub** [gen2brain/raylib-go#109]
I am trying to render PBR textures on a cube. They are not showing up. The cube is just white.
My program:
```go
package main

import rl "github.com/gen2brain/raylib-go/raylib"

func main() {
  WIDTH := int32(800)
  HEIGHT := int32(450)
  rl.InitWindow(WIDTH, HEIGHT, "3D")

  rl.SetTargetFPS(180)

  camera := rl.Camera{}
  camera.Position = rl.Vector3{ 4.0, 2.0, 4.0 }
  camera.Target = rl.Vector3{ 0.0, 0.0, 0.0 }
  camera.Up = rl.Vector3{ 0.0, 1.0, 0.0 }
  camera.Fovy = 45.0
  camera.Type = rl.CameraPerspective

  rl.SetCameraMode(camera, rl.CameraFirstPerson)

  floor := rl.LoadModelFromMesh(rl.GenMeshPlane(10, 10, 5, 5))
  cube := rl.LoadModelFromMesh(rl.GenMeshCube(2, 2, 2))

  diff := rl.LoadTexture("Maps/diff.jpg")
  ao := rl.LoadTexture("Maps/ao.jpg")
  disp := rl.LoadTexture("Maps/disp.jpg")
  norm := rl.LoadTexture("Maps/norm.jpg")
  rough := rl.LoadTexture("Maps/rough.jpg")

  cube.Materials = make([]rl.Material, 1)
  cube.Materials[0].Maps[rl.MapAlbedo].Color = rl.White
  cube.Materials[0].Maps[rl.MapDiffuse].Texture = diff
  cube.Materials[0].Maps[rl.MapOcclusion].Texture = ao
  cube.Materials[0].Maps[rl.MapHeight].Texture = disp
  cube.Materials[0].Maps[rl.MapNormal].Texture = norm
  cube.Materials[0].Maps[rl.MapRoughness].Texture = rough

  for !rl.WindowShouldClose() {
    rl.UpdateCamera(&camera)

    rl.BeginDrawing()
    rl.ClearBackground(rl.RayWhite)

    rl.BeginMode3D(camera)

    rl.DrawModel(floor, rl.Vector3{0, 0, 0}, 1, rl.Gray)

    rl.DrawModel(cube, rl.Vector3{0, 5, 0}, 1, rl.White)

    rl.EndMode3D()

    rl.EndDrawing()
  }

  rl.UnloadTexture(diff)
  rl.UnloadTexture(ao)
  rl.UnloadTexture(disp)
  rl.UnloadTexture(norm)
  rl.UnloadTexture(rough)

  rl.UnloadModel(floor)
  rl.UnloadModel(cube)

  rl.CloseWindow()
}
```

In addition, when I close the window, I get an error when trying to unload the cube, the one with the textures. If i get rid of the line that unloads the cube, I get no error. Error:
```
3d(96990,0xf889dc0) malloc: *** error for object 0x1: pointer being freed was not allocated
3d(96990,0xf889dc0) malloc: *** set a breakpoint in malloc_error_break to debug
SIGABRT: abort
PC=0x7fff685bb33a m=0 sigcode=0
signal arrived during cgo execution

goroutine 1 [syscall, locked to thread]:
runtime.cgocall(0x40b2050, 0xc00004f980, 0x29)
        /usr/local/Cellar/go/1.15/libexec/src/runtime/cgocall.go:133 +0x5b fp=0xc00004f8c8 sp=0xc00004f890 pc=0x4005c1b
github.com/gen2brain/raylib-go/raylib._Cfunc_UnloadModel(0x3f800000, 0x0, 0x3f80000000000000, 0x0, 0x0, 0x3f800000, 0x0, 0x3f80000000000000, 0x1, 0xbb5eef0, ...)
        _cgo_gotypes.go:4782 +0x56 fp=0xc00004f980 sp=0xc00004f8c8 pc=0x4099296
github.com/gen2brain/raylib-go/raylib.UnloadModel.func1(0xc00004fb28)
        go/src/github.com/gen2brain/raylib-go/raylib/models.go:195 +0xda fp=0xc00004fb10 sp=0xc00004f980 pc=0x4099c9a
github.com/gen2brain/raylib-go/raylib.UnloadModel(0x3f800000, 0x0, 0x3f80000000000000, 0x0, 0x0, 0x3f800000, 0x0, 0x3f80000000000000, 0x1, 0xbb5eef0, ...)
       go/src/github.com/gen2brain/raylib-go/raylib/models.go:195 +0x2b fp=0xc00004fb28 sp=0xc00004fb10 pc=0x40996eb
main.main()
        /<Path>/3d.go:71 +0x93b fp=0xc00004ff88 sp=0xc00004fb28 pc=0x409bedb
runtime.main()
        /usr/local/Cellar/go/1.15/libexec/src/runtime/proc.go:204 +0x209 fp=0xc00004ffe0 sp=0xc00004ff88 pc=0x4037229
runtime.goexit()
        /usr/local/Cellar/go/1.15/libexec/src/runtime/asm_amd64.s:1374 +0x1 fp=0xc00004ffe8 sp=0xc00004ffe0 pc=0x4065721

rax    0x0
rbx    0xf889dc0
rcx    0x7ffeefbff3c8
rdx    0x0
rdi    0x307
rsi    0x6
rbp    0x7ffeefbff3f0
rsp    0x7ffeefbff3c8
r8     0x0
r9     0x0
r10    0xf889dc0
r11    0x246
r12    0x307
r13    0x50
r14    0x6
r15    0x16
rip    0x7fff685bb33a
rflags 0x246
cs     0x7
fs     0x0
gs     0x0
exit status 2
```

**Comment by gen2brain** [comment]
This issue is a duplicate of #72

**Comment by Nv7-GitHub** [comment]
Ok, I am closing
