### ISSUE TITLE
Trying to load a texture but it panics

### ISSUE THREAD

**Issue by rafaelcn** [gen2brain/raylib-go#182]
I'm trying to load a texture from a `*rl.Image`  correctly loaded with the following code:

![image](https://user-images.githubusercontent.com/3271143/172746952-e0babefc-174c-44d3-b62c-844f060c7bf3.png)

The stack trace of the program after execution follows.

```
go run .
INFO: FILEIO: [res/ship.png] File loaded successfully
INFO: IMAGE: Data loaded successfully (15x15 | R8G8B8A8 | 1 mipmaps)
fatal error: unexpected signal during runtime execution
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x0]

runtime stack:
runtime.throw(0x5da622, 0x2a)
        /usr/local/go/src/runtime/panic.go:1117 +0x72
runtime.sigpanic()
        /usr/local/go/src/runtime/signal_unix.go:718 +0x2e5

goroutine 1 [syscall, locked to thread]:
runtime.cgocall(0x4eb500, 0xc000059df0, 0xc00000e048)
        /usr/local/go/src/runtime/cgocall.go:154 +0x5b fp=0xc000059da0 sp=0xc000059d68 pc=0x4359fb
github.com/gen2brain/raylib-go/raylib._Cfunc_LoadTextureFromImage(0x17e6a20, 0xf0000000f, 0x700000001, 0x0, 0x0, 0x0)
        _cgo_gotypes.go:4628 +0x51 fp=0xc000059df0 sp=0xc000059da0 pc=0x4cccf1
github.com/gen2brain/raylib-go/raylib.LoadTextureFromImage.func1(0xc00000e030, 0x0, 0x0, 0x0)
        /home/ranu/Programming/go/pkg/mod/github.com/gen2brain/raylib-go/raylib@v0.0.0-20220601234331-25dea46fc2d9/rtextures.go:99 +0xbd fp=0xc000059e78 sp=0xc000059df0 pc=0x4cd97d
github.com/gen2brain/raylib-go/raylib.LoadTextureFromImage(0xc00000e030, 0x0, 0x0, 0x0)
        /home/ranu/Programming/go/pkg/mod/github.com/gen2brain/raylib-go/raylib@v0.0.0-20220601234331-25dea46fc2d9/rtextures.go:99 +0x3c fp=0xc000059ec0 sp=0xc000059e78 pc=0x4cd3fc
```

I'm not sure what went wrong, but it isn't working correctly.

**Comment by rafaelcn** [comment]
If I remove the `rl.LoadTextureFromImage` call it loads the image though...

```
go run .
INFO: FILEIO: [res/ship.png] File loaded successfully
INFO: IMAGE: Data loaded successfully (15x15 | R8G8B8A8 | 1 mipmaps)
INFO: Initializing raylib 4.0
INFO: DISPLAY: Device initialized successfully
INFO:     > Display size: 1920 x 1080
INFO:     > Screen size:  800 x 640
INFO:     > Render size:  800 x 640
INFO:     > Viewport offsets: 0, 0
INFO: GLAD: OpenGL extensions loaded successfully
INFO: GL: Supported extensions count: 225
INFO: GL: OpenGL device information:
INFO:     > Vendor:   Intel
INFO:     > Renderer: Mesa Intel(R) HD Graphics 630 (KBL GT2)
INFO:     > Version:  4.6 (Core Profile) Mesa 21.2.6
INFO:     > GLSL:     4.60
INFO: GL: DXT compressed textures supported
INFO: GL: ETC2/EAC compressed textures supported
INFO: TEXTURE: [ID 1] Texture loaded successfully (1x1 | R8G8B8A8 | 1 mipmaps)
INFO: TEXTURE: [ID 1] Default texture loaded successfully
INFO: SHADER: [ID 1] Vertex shader compiled successfully
INFO: SHADER: [ID 2] Fragment shader compiled successfully
INFO: SHADER: [ID 3] Program shader loaded successfully
INFO: SHADER: [ID 3] Default shader loaded successfully
INFO: RLGL: Render batch vertex buffers loaded successfully in RAM (CPU)
INFO: RLGL: Render batch vertex buffers loaded successfully in VRAM (GPU)
INFO: RLGL: Default OpenGL state initialized successfully
INFO: TEXTURE: [ID 2] Texture loaded successfully (128x128 | GRAY_ALPHA | 1 mipmaps)
INFO: FONT: Default font loaded successfully (224 glyphs)
INFO: TIMER: Target time per frame: 16.667 milliseconds
INFO: TEXTURE: [ID 2] Unloaded texture data from VRAM (GPU)
INFO: SHADER: [ID 3] Default shader unloaded successfully
INFO: TEXTURE: [ID 1] Default texture unloaded successfully
INFO: Window closed successfully
```
The texture with ID 1 and ID 2 are unknown to me as the image I'm trying to load is  15x15 pixels wide.

**Comment by gen2brain** [comment]
Can you try with some of the available examples, does it crash again, or is it just your app?  That function will convert the image to texture and upload it to GPU, so it looks like some driver issue.

**Comment by JupiterRider** [comment]
You have to InitWindow before loading a texture!

InitWindow loads the OpenGL Context and a texture is a picture in the GPU VRAM

**Comment by rafaelcn** [comment]
Let me test it on the original code and I myself will close if that's the case. I tested the texture example on the library itself and it worked so it might be that.

**Comment by rafaelcn** [comment]
@gen2brain, my code already contains window initialization but it was being called after asset loading and that was the error. Thanks for the heads up @JupiterRider!
