### ISSUE TITLE
LoadFontEx Causes Immediate Crash

### ISSUE THREAD

**Issue by broccoligamedev** [gen2brain/raylib-go#260]
Issue: Using LoadFontEx causes the program to immediately crash with the follow error message. I'm using the most recent version of the bindings.

```
INFO: FILEIO: [fonts/luckiest_guy.ttf] File loaded successfully
Exception 0xc0000005 0x8 0x0 0x0
PC=0x0
signal arrived during external code execution

runtime.cgocall(0x7ff7026e4670, 0xc000115cd0)
        C:/Program Files/Go/src/runtime/cgocall.go:157 +0x4a fp=0xc000115ca8 sp=0xc000115c70 pc=0x7ff702633eca
github.com/gen2brain/raylib-go/raylib._Cfunc_LoadFontEx(0x1e7baef1730, 0x10, 0xc000122000, 0x24)
        _cgo_gotypes.go:4761 +0x6c fp=0xc000115cd0 sp=0xc000115ca8 pc=0x7ff7026c4a2c
github.com/gen2brain/raylib-go/raylib.LoadFontEx({0x7ff70283e64a?, 0x7ff702836840?}, 0x57e18?, {0xc000122000?, 0x24, 0xc000057e40?})
        C:/Users/ryanh/go/pkg/mod/github.com/gen2brain/raylib-go/raylib@v0.0.0-20230511170620-d84e4cc82f8d/rtext.go:51 +0xd1 fp=0xc000115d80 sp=0xc000115cd0 pc=0x7ff7026c5451
main.load()
        C:/Users/ryanh/desktop/code/raylib-test/main.go:79 +0x27e fp=0xc000115f40 sp=0xc000115d80 pc=0x7ff7026c6a3e
main.main()
        C:/Users/ryanh/desktop/code/raylib-test/main.go:17 +0x1d fp=0xc000115f80 sp=0xc000115f40 pc=0x7ff7026c643d
runtime.main()
        C:/Program Files/Go/src/runtime/proc.go:250 +0x1f7 fp=0xc000115fe0 sp=0xc000115f80 pc=0x7ff702667717
runtime.goexit()
        C:/Program Files/Go/src/runtime/asm_amd64.s:1598 +0x1 fp=0xc000115fe8 sp=0xc000115fe0 pc=0x7ff70268faa1

goroutine 2 [force gc (idle)]:
runtime.gopark(0x0?, 0x0?, 0x0?, 0x0?, 0x0?)
        C:/Program Files/Go/src/runtime/proc.go:381 +0xd6 fp=0xc000053fb0 sp=0xc000053f90 pc=0x7ff702667b36
runtime.goparkunlock(...)
        C:/Program Files/Go/src/runtime/proc.go:387
runtime.forcegchelper()
        C:/Program Files/Go/src/runtime/proc.go:305 +0xb2 fp=0xc000053fe0 sp=0xc000053fb0 pc=0x7ff702667952
runtime.goexit()
        C:/Program Files/Go/src/runtime/asm_amd64.s:1598 +0x1 fp=0xc000053fe8 sp=0xc000053fe0 pc=0x7ff70268faa1
created by runtime.init.6
        C:/Program Files/Go/src/runtime/proc.go:293 +0x25

goroutine 3 [GC sweep wait]:
runtime.gopark(0x0?, 0x0?, 0x0?, 0x0?, 0x0?)
        C:/Program Files/Go/src/runtime/proc.go:381 +0xd6 fp=0xc000055f80 sp=0xc000055f60 pc=0x7ff702667b36
runtime.goparkunlock(...)
        C:/Program Files/Go/src/runtime/proc.go:387
runtime.bgsweep(0x0?)
        C:/Program Files/Go/src/runtime/mgcsweep.go:278 +0x8e fp=0xc000055fc8 sp=0xc000055f80 pc=0x7ff70265286e
runtime.gcenable.func1()
        C:/Program Files/Go/src/runtime/mgc.go:178 +0x26 fp=0xc000055fe0 sp=0xc000055fc8 pc=0x7ff702647c86
runtime.goexit()
        C:/Program Files/Go/src/runtime/asm_amd64.s:1598 +0x1 fp=0xc000055fe8 sp=0xc000055fe0 pc=0x7ff70268faa1
created by runtime.gcenable
        C:/Program Files/Go/src/runtime/mgc.go:178 +0x6b

goroutine 4 [GC scavenge wait]:
runtime.gopark(0xc000060000?, 0x7ff70285c6d8?, 0x1?, 0x0?, 0x0?)
        C:/Program Files/Go/src/runtime/proc.go:381 +0xd6 fp=0xc000067f70 sp=0xc000067f50 pc=0x7ff702667b36
runtime.goparkunlock(...)
        C:/Program Files/Go/src/runtime/proc.go:387
runtime.(*scavengerState).park(0x7ff702936020)
        C:/Program Files/Go/src/runtime/mgcscavenge.go:400 +0x53 fp=0xc000067fa0 sp=0xc000067f70 pc=0x7ff702650773
runtime.bgscavenge(0x0?)
        C:/Program Files/Go/src/runtime/mgcscavenge.go:628 +0x45 fp=0xc000067fc8 sp=0xc000067fa0 pc=0x7ff702650d65
runtime.gcenable.func2()
        C:/Program Files/Go/src/runtime/mgc.go:179 +0x26 fp=0xc000067fe0 sp=0xc000067fc8 pc=0x7ff702647c26
runtime.goexit()
        C:/Program Files/Go/src/runtime/asm_amd64.s:1598 +0x1 fp=0xc000067fe8 sp=0xc000067fe0 pc=0x7ff70268faa1
created by runtime.gcenable
        C:/Program Files/Go/src/runtime/mgc.go:179 +0xaa

goroutine 5 [finalizer wait]:
runtime.gopark(0x1a0?, 0x7ff702936560?, 0xa0?, 0xe?, 0xc000057f70?)
        C:/Program Files/Go/src/runtime/proc.go:381 +0xd6 fp=0xc000057e28 sp=0xc000057e08 pc=0x7ff702667b36
runtime.runfinq()
        C:/Program Files/Go/src/runtime/mfinal.go:193 +0x107 fp=0xc000057fe0 sp=0xc000057e28 pc=0x7ff702646ce7
runtime.goexit()
        C:/Program Files/Go/src/runtime/asm_amd64.s:1598 +0x1 fp=0xc000057fe8 sp=0xc000057fe0 pc=0x7ff70268faa1
created by runtime.createfing
        C:/Program Files/Go/src/runtime/mfinal.go:163 +0x45
rax     0x9a4e1ff7f0
rbx     0x100
rcx     0xde1
rdi     0x2
rsi     0x100
rbp     0x1
rsp     0x9a4e1ff638
r8      0x100
r9      0x2
r10     0x0
r11     0x9a4e1ff5f0
r12     0x2
r13     0x1e7e0a10080
r14     0x9a4e1ff7f0
r15     0x36
rip     0x0
rflags  0x10246
cs      0x33
fs      0x53
gs      0x2b
```

**Comment by broccoligamedev** [comment]
Issue was caused by not calling InitWindow before loading LoadFontEx.
