### ISSUE TITLE
Opening a blank window in a test eventually crashes on Windows

### ISSUE THREAD

**Issue by scallyw4g** [gen2brain/raylib-go#265]
I'm doing some super basic text rendering.  As I was working, I noticed the program started crashing intermittently.

As I pushed further, it started crashing more frequently.  After I was drawing ~1000? glyphs it would crash after a handful of seconds.

I backtracked until I had literally nothing but the example program that opens a window and draws the "hello world" text to the screen.  I even removed the text drawing, such that the program only loops, calling BeginDrawing, ClearBackground, EndDrawing.  This program usually crashes after running continuously for about 5 minutes on my machine, though sometimes it runs for as many as 10.

This only happens when running a test.  If you run the program normally it works fine.  Is this me being ignorant of something go is doing under the hood?  I'm quite new to go, though I've been programming C and C++ for 10 years.

Windows 11

```
INFO: Initializing raylib 4.5
INFO: Supported raylib modules:
INFO:     > rcore:..... loaded (mandatory)
INFO:     > rlgl:...... loaded (mandatory)
INFO:     > rshapes:... loaded (optional)
INFO:     > rtextures:. loaded (optional)
INFO:     > rtext:..... loaded (optional)
INFO:     > rmodels:... loaded (optional)
INFO:     > raudio:.... loaded (optional)
INFO: DISPLAY: Device initialized successfully
INFO:     > Display size: 1920 x 1080
INFO:     > Screen size:  1600 x 900
INFO:     > Render size:  1600 x 900
INFO:     > Viewport offsets: 0, 0
INFO: GLAD: OpenGL extensions loaded successfully
INFO: GL: Supported extensions count: 402
INFO: GL: OpenGL device information:
INFO:     > Vendor:   NVIDIA Corporation
INFO:     > Renderer: NVIDIA GeForce RTX 3070 Ti Laptop GPU/PCIe/SSE2
INFO:     > Version:  3.3.0 NVIDIA 528.79
INFO:     > GLSL:     3.30 NVIDIA via Cg compiler
INFO: GL: VAO extension detected, VAO functions loaded successfully
INFO: GL: NPOT textures extension detected, full NPOT textures supported
INFO: GL: DXT compressed textures supported
INFO: GL: ETC2/EAC compressed textures supported
INFO: TEXTURE: [ID 1] Texture loaded successfully (1x1 | R8G8B8A8 | 1 mipmaps)
INFO: TEXTURE: [ID 1] Default texture loaded successfully
INFO: SHADER: [ID 1] Vertex shader compiled successfully
INFO: SHADER: [ID 2] Fragment shader compiled successfully
INFO: SHADER: [ID 3] Program shader loaded successfully
INFO: SHADER: [ID 3] Default shader loaded successfully
INFO: RLGL: Render batch vertex buffers loaded successfully in RAM (CPU)
INFO: RLGL: Render batch vertex buffers loaded successfully in VRAM (GPU)
INFO: RLGL: Default OpenGL state initialized successfully
INFO: TEXTURE: [ID 2] Texture loaded successfully (128x128 | GRAY_ALPHA | 1 mipmaps)
INFO: FONT: Default font loaded successfully (224 glyphs)
INFO: TIMER: Target time per frame: 16.667 milliseconds

... several minutes later ...

Exception 0xc0000005 0x0 0x1580 0x7fff3bb1fa29
PC=0x7fff3bb1fa29
signal arrived during external code execution

runtime.cgocall(0x7ff7c7e94a90, 0xc000107488)
        C:/Program Files/Go/src/runtime/cgocall.go:157 +0x4a fp=0xc000107460 sp=0xc000107428 pc=0x7ff7c7d54cca
github.com/gen2brain/raylib-go/raylib._Cfunc_EndDrawing()
        _cgo_gotypes.go:2115 +0x4a fp=0xc000107488 sp=0xc000107460 pc=0x7ff7c7e6dfca
github.com/gen2brain/raylib-go/raylib.EndDrawing(...)
        C:/Users/<redacted>/go/pkg/mod/github.com/gen2brain/raylib-go/raylib@v0.0.0-20230606094659-048c1b598cb2/rcore.go:368
github.com/<redacted>(0xc000081800)
        C:/Users/<redacted>.go:387 +0x97 fp=0xc000107550 sp=0xc000107488 pc=0x7ff7c7e702d7
github.com/<redacted>(0xc000081800)
        C:/Users/<redacted>.go:457 +0x8b fp=0xc0001075e8 sp=0xc000107550 pc=0x7ff7c7e70e0b
github.com/<redacted>(0xc000081800)
        C:/Users/<redacted>.go:556 +0xbf fp=0xc000107668 sp=0xc0001075e8 pc=0x7ff7c7e7175f
github.com/<redacted>(0xc000081800?, 0x1?)
        C:/Users/<redacted>.go:234 +0xd5 fp=0xc0001076d0 sp=0xc000107668 pc=0x7ff7c7e71c95
github.com/<redacted>(0xc0001078c0, 0xc00000a018?, 0x0, 0x1f?, 0x0, 0xa?, 0x0)
        C:/Users/<redacted>l.go:182 +0x328 fp=0xc000107868 sp=0xc0001076d0 pc=0x7ff7c7e75ca8
github.com/<redacted>({0x7ff7c8012566, 0x11})
        C:/Users/<redacted>.go:92 +0x73b fp=0xc000107d50 sp=0xc000107868 pc=0x7ff7c7e7c13b
github.com/<redacted>(0x0?)
        C:/Users/<redacted>.go:45 +0x41d fp=0xc000107f70 sp=0xc000107d50 pc=0x7ff7c7e7d15d
testing.tRunner(0xc0000616c0, 0x7ff7c801d9d0)
        C:/Program Files/Go/src/testing/testing.go:1576 +0x10b fp=0xc000107fc0 sp=0xc000107f70 pc=0x7ff7c7e2b52b
testing.(*T).Run.func1()
        C:/Program Files/Go/src/testing/testing.go:1629 +0x2a fp=0xc000107fe0 sp=0xc000107fc0 pc=0x7ff7c7e2c56a
runtime.goexit()
        C:/Program Files/Go/src/runtime/asm_amd64.s:1598 +0x1 fp=0xc000107fe8 sp=0xc000107fe0 pc=0x7ff7c7dba261
created by testing.(*T).Run
        C:/Program Files/Go/src/testing/testing.go:1629 +0x3ea

goroutine 1 [chan receive, locked to thread]:
runtime.gopark(0x7ff7c816e1a0?, 0xc00000a0a0?, 0xf0?, 0x28?, 0xc000123a28?)
        C:/Program Files/Go/src/runtime/proc.go:381 +0xd6 fp=0xc0000719a8 sp=0xc000071988 pc=0x7ff7c7d8c556
runtime.chanrecv(0xc00001c150, 0xc000123aa7, 0x1)
        C:/Program Files/Go/src/runtime/chan.go:583 +0x49d fp=0xc000071a38 sp=0xc0000719a8 pc=0x7ff7c7d57afd
runtime.chanrecv1(0x7ff7c816d6a0?, 0x7ff7c7fe78a0?)
        C:/Program Files/Go/src/runtime/chan.go:442 +0x18 fp=0xc000071a60 sp=0xc000071a38 pc=0x7ff7c7d57638
testing.(*T).Run(0xc000061520, {0x7ff7c8010091?, 0x7ff7c7dbcdb3?}, 0x7ff7c801d9d0)
        C:/Program Files/Go/src/testing/testing.go:1630 +0x405 fp=0xc000071b20 sp=0xc000071a60 pc=0x7ff7c7e2c3e5
testing.runTests.func1(0x7ff7c816e1a0?)
        C:/Program Files/Go/src/testing/testing.go:2036 +0x45 fp=0xc000071b70 sp=0xc000071b20 pc=0x7ff7c7e2e545
testing.tRunner(0xc000061520, 0xc000123c88)
        C:/Program Files/Go/src/testing/testing.go:1576 +0x10b fp=0xc000071bc0 sp=0xc000071b70 pc=0x7ff7c7e2b52b
testing.runTests(0xc0000261e0?, {0x7ff7c7fcc790, 0x1, 0x1}, {0x20?, 0x100c00012e548?, 0x7ff7c816d8c0?})
        C:/Program Files/Go/src/testing/testing.go:2034 +0x489 fp=0xc000071cb8 sp=0xc000071bc0 pc=0x7ff7c7e2e429
testing.(*M).Run(0xc0000261e0)
        C:/Program Files/Go/src/testing/testing.go:1906 +0x63a fp=0xc000071f00 sp=0xc000071cb8 pc=0x7ff7c7e2cd9a
main.main()
        _testmain.go:47 +0x1aa fp=0xc000071f80 sp=0xc000071f00 pc=0x7ff7c7e7d3ca
runtime.main()
        C:/Program Files/Go/src/runtime/proc.go:250 +0x1f7 fp=0xc000071fe0 sp=0xc000071f80 pc=0x7ff7c7d8c137
runtime.goexit()
        C:/Program Files/Go/src/runtime/asm_amd64.s:1598 +0x1 fp=0xc000071fe8 sp=0xc000071fe0 pc=0x7ff7c7dba261

goroutine 2 [force gc (idle)]:
runtime.gopark(0x0?, 0x0?, 0x0?, 0x0?, 0x0?)
        C:/Program Files/Go/src/runtime/proc.go:381 +0xd6 fp=0xc000063fb0 sp=0xc000063f90 pc=0x7ff7c7d8c556
runtime.goparkunlock(...)
        C:/Program Files/Go/src/runtime/proc.go:387
runtime.forcegchelper()
        C:/Program Files/Go/src/runtime/proc.go:305 +0xb2 fp=0xc000063fe0 sp=0xc000063fb0 pc=0x7ff7c7d8c372
runtime.goexit()
        C:/Program Files/Go/src/runtime/asm_amd64.s:1598 +0x1 fp=0xc000063fe8 sp=0xc000063fe0 pc=0x7ff7c7dba261
created by runtime.init.6
        C:/Program Files/Go/src/runtime/proc.go:293 +0x25

goroutine 3 [GC sweep wait]:
runtime.gopark(0x1?, 0x0?, 0x0?, 0x0?, 0x0?)
        C:/Program Files/Go/src/runtime/proc.go:381 +0xd6 fp=0xc000065f80 sp=0xc000065f60 pc=0x7ff7c7d8c556
runtime.goparkunlock(...)
        C:/Program Files/Go/src/runtime/proc.go:387
runtime.bgsweep(0x0?)
        C:/Program Files/Go/src/runtime/mgcsweep.go:319 +0xde fp=0xc000065fc8 sp=0xc000065f80 pc=0x7ff7c7d74cde
runtime.gcenable.func1()
        C:/Program Files/Go/src/runtime/mgc.go:178 +0x26 fp=0xc000065fe0 sp=0xc000065fc8 pc=0x7ff7c7d69ea6
runtime.goexit()
        C:/Program Files/Go/src/runtime/asm_amd64.s:1598 +0x1 fp=0xc000065fe8 sp=0xc000065fe0 pc=0x7ff7c7dba261
created by runtime.gcenable
        C:/Program Files/Go/src/runtime/mgc.go:178 +0x6b

goroutine 4 [GC scavenge wait]:
runtime.gopark(0xc00001c070?, 0x7ff7c8043870?, 0x0?, 0x0?, 0x0?)
        C:/Program Files/Go/src/runtime/proc.go:381 +0xd6 fp=0xc000073f70 sp=0xc000073f50 pc=0x7ff7c7d8c556
runtime.goparkunlock(...)
        C:/Program Files/Go/src/runtime/proc.go:387
runtime.(*scavengerState).park(0x7ff7c816d940)
        C:/Program Files/Go/src/runtime/mgcscavenge.go:400 +0x53 fp=0xc000073fa0 sp=0xc000073f70 pc=0x7ff7c7d72b93
runtime.bgscavenge(0x0?)
        C:/Program Files/Go/src/runtime/mgcscavenge.go:633 +0x65 fp=0xc000073fc8 sp=0xc000073fa0 pc=0x7ff7c7d731a5
runtime.gcenable.func2()
        C:/Program Files/Go/src/runtime/mgc.go:179 +0x26 fp=0xc000073fe0 sp=0xc000073fc8 pc=0x7ff7c7d69e46
runtime.goexit()
        C:/Program Files/Go/src/runtime/asm_amd64.s:1598 +0x1 fp=0xc000073fe8 sp=0xc000073fe0 pc=0x7ff7c7dba261
created by runtime.gcenable
        C:/Program Files/Go/src/runtime/mgc.go:179 +0xaa

goroutine 5 [finalizer wait]:
runtime.gopark(0x1a0?, 0x7ff7c816e1a0?, 0xa0?, 0xe?, 0xc000067f70?)
        C:/Program Files/Go/src/runtime/proc.go:381 +0xd6 fp=0xc000067e28 sp=0xc000067e08 pc=0x7ff7c7d8c556
runtime.runfinq()
        C:/Program Files/Go/src/runtime/mfinal.go:193 +0x107 fp=0xc000067fe0 sp=0xc000067e28 pc=0x7ff7c7d68f07
runtime.goexit()
        C:/Program Files/Go/src/runtime/asm_amd64.s:1598 +0x1 fp=0xc000067fe8 sp=0xc000067fe0 pc=0x7ff7c7dba261
created by runtime.createfing
        C:/Program Files/Go/src/runtime/mfinal.go:163 +0x45

goroutine 18 [GC worker (idle)]:
runtime.gopark(0x0?, 0x0?, 0xb0?, 0x5f?, 0x7ff7c7e2b52b?)
        C:/Program Files/Go/src/runtime/proc.go:381 +0xd6 fp=0xc000075f50 sp=0xc000075f30 pc=0x7ff7c7d8c556
runtime.gcBgMarkWorker()
        C:/Program Files/Go/src/runtime/mgc.go:1275 +0xf1 fp=0xc000075fe0 sp=0xc000075f50 pc=0x7ff7c7d6bc51
runtime.goexit()
        C:/Program Files/Go/src/runtime/asm_amd64.s:1598 +0x1 fp=0xc000075fe8 sp=0xc000075fe0 pc=0x7ff7c7dba261
created by runtime.gcBgMarkStartWorkers
        C:/Program Files/Go/src/runtime/mgc.go:1199 +0x25

goroutine 34 [GC worker (idle)]:
runtime.gopark(0x0?, 0x0?, 0x0?, 0x0?, 0x0?)
        C:/Program Files/Go/src/runtime/proc.go:381 +0xd6 fp=0xc00006ff50 sp=0xc00006ff30 pc=0x7ff7c7d8c556
runtime.gcBgMarkWorker()
        C:/Program Files/Go/src/runtime/mgc.go:1275 +0xf1 fp=0xc00006ffe0 sp=0xc00006ff50 pc=0x7ff7c7d6bc51
runtime.goexit()
        C:/Program Files/Go/src/runtime/asm_amd64.s:1598 +0x1 fp=0xc00006ffe8 sp=0xc00006ffe0 pc=0x7ff7c7dba261
created by runtime.gcBgMarkStartWorkers
        C:/Program Files/Go/src/runtime/mgc.go:1199 +0x25

goroutine 19 [GC worker (idle)]:
runtime.gopark(0x0?, 0x0?, 0x0?, 0x0?, 0x0?)
        C:/Program Files/Go/src/runtime/proc.go:381 +0xd6 fp=0xc0000e7f50 sp=0xc0000e7f30 pc=0x7ff7c7d8c556
runtime.gcBgMarkWorker()
        C:/Program Files/Go/src/runtime/mgc.go:1275 +0xf1 fp=0xc0000e7fe0 sp=0xc0000e7f50 pc=0x7ff7c7d6bc51
runtime.goexit()
        C:/Program Files/Go/src/runtime/asm_amd64.s:1598 +0x1 fp=0xc0000e7fe8 sp=0xc0000e7fe0 pc=0x7ff7c7dba261
created by runtime.gcBgMarkStartWorkers
        C:/Program Files/Go/src/runtime/mgc.go:1199 +0x25

goroutine 20 [GC worker (idle)]:
runtime.gopark(0x0?, 0x0?, 0x0?, 0x0?, 0x0?)
        C:/Program Files/Go/src/runtime/proc.go:381 +0xd6 fp=0xc0000e9f50 sp=0xc0000e9f30 pc=0x7ff7c7d8c556
runtime.gcBgMarkWorker()
        C:/Program Files/Go/src/runtime/mgc.go:1275 +0xf1 fp=0xc0000e9fe0 sp=0xc0000e9f50 pc=0x7ff7c7d6bc51
runtime.goexit()
        C:/Program Files/Go/src/runtime/asm_amd64.s:1598 +0x1 fp=0xc0000e9fe8 sp=0xc0000e9fe0 pc=0x7ff7c7dba261
created by runtime.gcBgMarkStartWorkers
        C:/Program Files/Go/src/runtime/mgc.go:1199 +0x25

goroutine 21 [GC worker (idle)]:
runtime.gopark(0x0?, 0x0?, 0x0?, 0x0?, 0x0?)
        C:/Program Files/Go/src/runtime/proc.go:381 +0xd6 fp=0xc0000e3f50 sp=0xc0000e3f30 pc=0x7ff7c7d8c556
runtime.gcBgMarkWorker()
        C:/Program Files/Go/src/runtime/mgc.go:1275 +0xf1 fp=0xc0000e3fe0 sp=0xc0000e3f50 pc=0x7ff7c7d6bc51
runtime.goexit()
        C:/Program Files/Go/src/runtime/asm_amd64.s:1598 +0x1 fp=0xc0000e3fe8 sp=0xc0000e3fe0 pc=0x7ff7c7dba261
created by runtime.gcBgMarkStartWorkers
        C:/Program Files/Go/src/runtime/mgc.go:1199 +0x25

goroutine 7 [GC worker (idle)]:
runtime.gopark(0x0?, 0x0?, 0x0?, 0x0?, 0x0?)
        C:/Program Files/Go/src/runtime/proc.go:381 +0xd6 fp=0xc000147f50 sp=0xc000147f30 pc=0x7ff7c7d8c556
runtime.gcBgMarkWorker()
        C:/Program Files/Go/src/runtime/mgc.go:1275 +0xf1 fp=0xc000147fe0 sp=0xc000147f50 pc=0x7ff7c7d6bc51
runtime.goexit()
        C:/Program Files/Go/src/runtime/asm_amd64.s:1598 +0x1 fp=0xc000147fe8 sp=0xc000147fe0 pc=0x7ff7c7dba261
created by runtime.gcBgMarkStartWorkers
        C:/Program Files/Go/src/runtime/mgc.go:1199 +0x25

goroutine 8 [GC worker (idle)]:
runtime.gopark(0x0?, 0x0?, 0x0?, 0x0?, 0x0?)
        C:/Program Files/Go/src/runtime/proc.go:381 +0xd6 fp=0xc000149f50 sp=0xc000149f30 pc=0x7ff7c7d8c556
runtime.gcBgMarkWorker()
        C:/Program Files/Go/src/runtime/mgc.go:1275 +0xf1 fp=0xc000149fe0 sp=0xc000149f50 pc=0x7ff7c7d6bc51
runtime.goexit()
        C:/Program Files/Go/src/runtime/asm_amd64.s:1598 +0x1 fp=0xc000149fe8 sp=0xc000149fe0 pc=0x7ff7c7dba261
created by runtime.gcBgMarkStartWorkers
        C:/Program Files/Go/src/runtime/mgc.go:1199 +0x25

goroutine 9 [GC worker (idle)]:
runtime.gopark(0x0?, 0x0?, 0x0?, 0x0?, 0x0?)
        C:/Program Files/Go/src/runtime/proc.go:381 +0xd6 fp=0xc000143f50 sp=0xc000143f30 pc=0x7ff7c7d8c556
runtime.gcBgMarkWorker()
        C:/Program Files/Go/src/runtime/mgc.go:1275 +0xf1 fp=0xc000143fe0 sp=0xc000143f50 pc=0x7ff7c7d6bc51
runtime.goexit()
        C:/Program Files/Go/src/runtime/asm_amd64.s:1598 +0x1 fp=0xc000143fe8 sp=0xc000143fe0 pc=0x7ff7c7dba261
created by runtime.gcBgMarkStartWorkers
        C:/Program Files/Go/src/runtime/mgc.go:1199 +0x25

goroutine 10 [GC worker (idle)]:
runtime.gopark(0x0?, 0x0?, 0x0?, 0x0?, 0x0?)
        C:/Program Files/Go/src/runtime/proc.go:381 +0xd6 fp=0xc000145f50 sp=0xc000145f30 pc=0x7ff7c7d8c556
runtime.gcBgMarkWorker()
        C:/Program Files/Go/src/runtime/mgc.go:1275 +0xf1 fp=0xc000145fe0 sp=0xc000145f50 pc=0x7ff7c7d6bc51
runtime.goexit()
        C:/Program Files/Go/src/runtime/asm_amd64.s:1598 +0x1 fp=0xc000145fe8 sp=0xc000145fe0 pc=0x7ff7c7dba261
created by runtime.gcBgMarkStartWorkers
        C:/Program Files/Go/src/runtime/mgc.go:1199 +0x25

goroutine 11 [GC worker (idle)]:
runtime.gopark(0x0?, 0x0?, 0x0?, 0x0?, 0x0?)
        C:/Program Files/Go/src/runtime/proc.go:381 +0xd6 fp=0xc000151f50 sp=0xc000151f30 pc=0x7ff7c7d8c556
runtime.gcBgMarkWorker()
        C:/Program Files/Go/src/runtime/mgc.go:1275 +0xf1 fp=0xc000151fe0 sp=0xc000151f50 pc=0x7ff7c7d6bc51
runtime.goexit()
        C:/Program Files/Go/src/runtime/asm_amd64.s:1598 +0x1 fp=0xc000151fe8 sp=0xc000151fe0 pc=0x7ff7c7dba261
created by runtime.gcBgMarkStartWorkers
        C:/Program Files/Go/src/runtime/mgc.go:1199 +0x25

goroutine 12 [GC worker (idle)]:
runtime.gopark(0x0?, 0x0?, 0x0?, 0x0?, 0x0?)
        C:/Program Files/Go/src/runtime/proc.go:381 +0xd6 fp=0xc000153f50 sp=0xc000153f30 pc=0x7ff7c7d8c556
runtime.gcBgMarkWorker()
        C:/Program Files/Go/src/runtime/mgc.go:1275 +0xf1 fp=0xc000153fe0 sp=0xc000153f50 pc=0x7ff7c7d6bc51
runtime.goexit()
        C:/Program Files/Go/src/runtime/asm_amd64.s:1598 +0x1 fp=0xc000153fe8 sp=0xc000153fe0 pc=0x7ff7c7dba261
created by runtime.gcBgMarkStartWorkers
        C:/Program Files/Go/src/runtime/mgc.go:1199 +0x25

goroutine 50 [GC worker (idle)]:
runtime.gopark(0x0?, 0x0?, 0x0?, 0x0?, 0x0?)
        C:/Program Files/Go/src/runtime/proc.go:381 +0xd6 fp=0xc00014df50 sp=0xc00014df30 pc=0x7ff7c7d8c556
runtime.gcBgMarkWorker()
        C:/Program Files/Go/src/runtime/mgc.go:1275 +0xf1 fp=0xc00014dfe0 sp=0xc00014df50 pc=0x7ff7c7d6bc51
runtime.goexit()
        C:/Program Files/Go/src/runtime/asm_amd64.s:1598 +0x1 fp=0xc00014dfe8 sp=0xc00014dfe0 pc=0x7ff7c7dba261
created by runtime.gcBgMarkStartWorkers
        C:/Program Files/Go/src/runtime/mgc.go:1199 +0x25

goroutine 13 [GC worker (idle)]:
runtime.gopark(0x0?, 0x0?, 0x0?, 0x0?, 0x0?)
        C:/Program Files/Go/src/runtime/proc.go:381 +0xd6 fp=0xc00015bf50 sp=0xc00015bf30 pc=0x7ff7c7d8c556
runtime.gcBgMarkWorker()
        C:/Program Files/Go/src/runtime/mgc.go:1275 +0xf1 fp=0xc00015bfe0 sp=0xc00015bf50 pc=0x7ff7c7d6bc51
runtime.goexit()
        C:/Program Files/Go/src/runtime/asm_amd64.s:1598 +0x1 fp=0xc00015bfe8 sp=0xc00015bfe0 pc=0x7ff7c7dba261
created by runtime.gcBgMarkStartWorkers
        C:/Program Files/Go/src/runtime/mgc.go:1199 +0x25

goroutine 14 [GC worker (idle)]:
runtime.gopark(0x0?, 0x0?, 0x0?, 0x0?, 0x0?)
        C:/Program Files/Go/src/runtime/proc.go:381 +0xd6 fp=0xc00015df50 sp=0xc00015df30 pc=0x7ff7c7d8c556
runtime.gcBgMarkWorker()
        C:/Program Files/Go/src/runtime/mgc.go:1275 +0xf1 fp=0xc00015dfe0 sp=0xc00015df50 pc=0x7ff7c7d6bc51
runtime.goexit()
        C:/Program Files/Go/src/runtime/asm_amd64.s:1598 +0x1 fp=0xc00015dfe8 sp=0xc00015dfe0 pc=0x7ff7c7dba261
created by runtime.gcBgMarkStartWorkers
        C:/Program Files/Go/src/runtime/mgc.go:1199 +0x25

goroutine 15 [GC worker (idle)]:
runtime.gopark(0x145523a4d3f0?, 0x0?, 0x0?, 0x0?, 0x0?)
        C:/Program Files/Go/src/runtime/proc.go:381 +0xd6 fp=0xc000157f50 sp=0xc000157f30 pc=0x7ff7c7d8c556
runtime.gcBgMarkWorker()
        C:/Program Files/Go/src/runtime/mgc.go:1275 +0xf1 fp=0xc000157fe0 sp=0xc000157f50 pc=0x7ff7c7d6bc51
runtime.goexit()
        C:/Program Files/Go/src/runtime/asm_amd64.s:1598 +0x1 fp=0xc000157fe8 sp=0xc000157fe0 pc=0x7ff7c7dba261
created by runtime.gcBgMarkStartWorkers
        C:/Program Files/Go/src/runtime/mgc.go:1199 +0x25

goroutine 22 [GC worker (idle)]:
runtime.gopark(0x7ff7c81c3540?, 0x1?, 0x68?, 0xe?, 0x0?)
        C:/Program Files/Go/src/runtime/proc.go:381 +0xd6 fp=0xc0000e5f50 sp=0xc0000e5f30 pc=0x7ff7c7d8c556
runtime.gcBgMarkWorker()
        C:/Program Files/Go/src/runtime/mgc.go:1275 +0xf1 fp=0xc0000e5fe0 sp=0xc0000e5f50 pc=0x7ff7c7d6bc51
runtime.goexit()
        C:/Program Files/Go/src/runtime/asm_amd64.s:1598 +0x1 fp=0xc0000e5fe8 sp=0xc0000e5fe0 pc=0x7ff7c7dba261
created by runtime.gcBgMarkStartWorkers
        C:/Program Files/Go/src/runtime/mgc.go:1199 +0x25

goroutine 16 [GC worker (idle)]:
runtime.gopark(0x7ff7c81c3540?, 0x1?, 0x44?, 0xdf?, 0x0?)
        C:/Program Files/Go/src/runtime/proc.go:381 +0xd6 fp=0xc000159f50 sp=0xc000159f30 pc=0x7ff7c7d8c556
runtime.gcBgMarkWorker()
        C:/Program Files/Go/src/runtime/mgc.go:1275 +0xf1 fp=0xc000159fe0 sp=0xc000159f50 pc=0x7ff7c7d6bc51
runtime.goexit()
        C:/Program Files/Go/src/runtime/asm_amd64.s:1598 +0x1 fp=0xc000159fe8 sp=0xc000159fe0 pc=0x7ff7c7dba261
created by runtime.gcBgMarkStartWorkers
        C:/Program Files/Go/src/runtime/mgc.go:1199 +0x25

goroutine 66 [GC worker (idle)]:
runtime.gopark(0x145523a63aec?, 0x3?, 0xfc?, 0x66?, 0x0?)
        C:/Program Files/Go/src/runtime/proc.go:381 +0xd6 fp=0xc000163f50 sp=0xc000163f30 pc=0x7ff7c7d8c556
runtime.gcBgMarkWorker()
        C:/Program Files/Go/src/runtime/mgc.go:1275 +0xf1 fp=0xc000163fe0 sp=0xc000163f50 pc=0x7ff7c7d6bc51
runtime.goexit()
        C:/Program Files/Go/src/runtime/asm_amd64.s:1598 +0x1 fp=0xc000163fe8 sp=0xc000163fe0 pc=0x7ff7c7dba261
created by runtime.gcBgMarkStartWorkers
        C:/Program Files/Go/src/runtime/mgc.go:1199 +0x25

goroutine 67 [GC worker (idle)]:
runtime.gopark(0x7ff7c81c3540?, 0x1?, 0x68?, 0xe?, 0x0?)
        C:/Program Files/Go/src/runtime/proc.go:381 +0xd6 fp=0xc000165f50 sp=0xc000165f30 pc=0x7ff7c7d8c556
runtime.gcBgMarkWorker()
        C:/Program Files/Go/src/runtime/mgc.go:1275 +0xf1 fp=0xc000165fe0 sp=0xc000165f50 pc=0x7ff7c7d6bc51
runtime.goexit()
        C:/Program Files/Go/src/runtime/asm_amd64.s:1598 +0x1 fp=0xc000165fe8 sp=0xc000165fe0 pc=0x7ff7c7dba261
created by runtime.gcBgMarkStartWorkers
        C:/Program Files/Go/src/runtime/mgc.go:1199 +0x25

goroutine 68 [GC worker (idle)]:
runtime.gopark(0x145523a63aec?, 0x3?, 0x0?, 0x0?, 0x0?)
        C:/Program Files/Go/src/runtime/proc.go:381 +0xd6 fp=0xc00015ff50 sp=0xc00015ff30 pc=0x7ff7c7d8c556
runtime.gcBgMarkWorker()
        C:/Program Files/Go/src/runtime/mgc.go:1275 +0xf1 fp=0xc00015ffe0 sp=0xc00015ff50 pc=0x7ff7c7d6bc51
runtime.goexit()
        C:/Program Files/Go/src/runtime/asm_amd64.s:1598 +0x1 fp=0xc00015ffe8 sp=0xc00015ffe0 pc=0x7ff7c7dba261
created by runtime.gcBgMarkStartWorkers
        C:/Program Files/Go/src/runtime/mgc.go:1199 +0x25
rax     0x0
rbx     0x7ff7c81d46e8
rcx     0x1
rdi     0xc000107488
rsi     0xc000684000
rbp     0xc000107450
rsp     0x99fbfff5e8
r8      0x264
r9      0x0
r10     0x3
r11     0x99fbfff8a0
r12     0xffffffffffffffff
r13     0xffffffffffffffff
r14     0xc000061860
r15     0x10
rip     0x7fff3bb1fa29
rflags  0x10206
cs      0x33
fs      0x53
gs      0x2b
exit status 2

```

**Comment by gen2brain** [comment]
As I understand, each test will run in its own goroutine,  note that the goroutine can arbitrarily and randomly be scheduled or rescheduled on different running threads. OpenGL is not thread-safe and is required to run on the main thread.

Not sure what you test in your tests? As you can see, there are no tests here, examples are the tests.

**Comment by jesse-lemurian** [comment]
Sounds plausible that's the issue.  Since running outside the test suite works fine I'm going to close this issue

**Comment by scallyw4g** [comment]
Sounds plausible that's the issue. Since running outside the test suite works fine I'm going to close this issue

**Comment by gen2brain** [comment]
For testing i.e., graphics or GUI `TestMain` can be used https://pkg.go.dev/testing#hdr-Main. Something like this:
```
func init() {
    runtime.LockOSThread()
}

func TestMain(m *testing.Main) {
    go func() {
        os.Exit(m.Run())
    }()
    runGraphics()
}
```
