### ISSUE TITLE
Intermittent SIGBUS: bus error When uploading a custom mesh to gpu

### ISSUE THREAD

**Issue by Dima-Kevanishvili** [gen2brain/raylib-go#359]
When uploading meshes really fast(at least I think it's when it's fast) I sometimes get a SIGBUS: bus error.

Go Version: go version go1.21.0 darwin/arm64
OS: MacOS Sonoma (M1 Pro Macbook)

Asked in discord and this was also reproducible on Windows 10.

If I use builtin `rl.GenMeshCube()` to create meshes instead of custom `createMesh` It either doesn't crash or it's so infrequent, i can't catch it 

Minimal Reproduction code:
```golang
package main

import (
	rl "github.com/gen2brain/raylib-go/raylib"
)

func createMesh() *rl.Mesh {
	verticies := []float32{0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 0, 1, 0, 1, 1, 1, 1, 0, 0, 1, 0, 1, 1, 0, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 0, 1, 0, 1, 1, 1, 1}
	indicies := []uint16{0, 1, 2, 2, 1, 3, 4, 5, 6, 6, 5, 7, 8, 9, 10, 10, 9, 11, 12, 13, 14, 14, 13, 15, 16, 17, 18, 18, 17, 19, 20, 21, 22, 22, 21, 23}
	mesh := rl.Mesh{
		Vertices:      &verticies[0],
		Indices:       &indicies[0],
		VertexCount:   72,
		TriangleCount: 12,
	}
	rl.UploadMesh(&mesh, false)

	return &mesh
}

func main() {
	rl.InitWindow(800, 450, "raylib [core] example - basic window")
	defer rl.CloseWindow()
	rl.SetTargetFPS(60)
	meshes := []*rl.Mesh{}
	for i := 0; i < 10000; i++ {
		mesh := createMesh()
		meshes = append(meshes, mesh)
	}

	for _, mesh := range meshes {
		rl.UnloadMesh(mesh)
	}
}

```

Stacktrace:
```
SIGBUS: bus error
PC=0x18384970c m=0 sigcode=1
signal arrived during cgo execution

goroutine 1 [syscall, locked to thread]:
runtime.cgocall(0x1042e6094, 0x14000058d98)
	/opt/homebrew/Cellar/go/1.21.0/libexec/src/runtime/cgocall.go:157 +0x44 fp=0x14000058d60 sp=0x14000058d20 pc=0x104248ca4
github.com/gen2brain/raylib-go/raylib._Cfunc_UploadMesh(0x140003fccb0, 0x0)
	_cgo_gotypes.go:6881 +0x30 fp=0x14000058d90 sp=0x14000058d60 pc=0x1042cd960
github.com/gen2brain/raylib-go/raylib.UploadMesh.func1(0x14000058e30?, 0x60?)
	/Users/****/go/pkg/mod/github.com/gen2brain/raylib-go/raylib@v0.0.0-20240125111008-83d871a38f28/rmodels.go:432 +0x50 fp=0x14000058dd0 sp=0x14000058d90 pc=0x1042cdf10
github.com/gen2brain/raylib-go/raylib.UploadMesh(0x140003fccb0, 0x0?)
	/Users/****/go/pkg/mod/github.com/gen2brain/raylib-go/raylib@v0.0.0-20240125111008-83d871a38f28/rmodels.go:432 +0x1b0 fp=0x14000058e50 sp=0x14000058dd0 pc=0x1042cddc0
main.createMesh()
	/Users/****/Desktop/Workspace/temp/tempgorl/main.go:16 +0x18c fp=0x14000058e90 sp=0x14000058e50 pc=0x1042ce87c
main.main()
	/Users/****/Desktop/Workspace/temp/tempgorl/main.go:27 +0xb0 fp=0x14000058f30 sp=0x14000058e90 pc=0x1042ce950
runtime.main()
	/opt/homebrew/Cellar/go/1.21.0/libexec/src/runtime/proc.go:267 +0x2bc fp=0x14000058fd0 sp=0x14000058f30 pc=0x10427909c
runtime.goexit()
	/opt/homebrew/Cellar/go/1.21.0/libexec/src/runtime/asm_arm64.s:1197 +0x4 fp=0x14000058fd0 sp=0x14000058fd0 pc=0x1042a4484

goroutine 2 [force gc (idle)]:
runtime.gopark(0x0?, 0x0?, 0x0?, 0x0?, 0x0?)
	/opt/homebrew/Cellar/go/1.21.0/libexec/src/runtime/proc.go:398 +0xc8 fp=0x14000048f90 sp=0x14000048f70 pc=0x1042794c8
runtime.goparkunlock(...)
	/opt/homebrew/Cellar/go/1.21.0/libexec/src/runtime/proc.go:404
runtime.forcegchelper()
	/opt/homebrew/Cellar/go/1.21.0/libexec/src/runtime/proc.go:322 +0xb8 fp=0x14000048fd0 sp=0x14000048f90 pc=0x104279358
runtime.goexit()
	/opt/homebrew/Cellar/go/1.21.0/libexec/src/runtime/asm_arm64.s:1197 +0x4 fp=0x14000048fd0 sp=0x14000048fd0 pc=0x1042a4484
created by runtime.init.6 in goroutine 1
	/opt/homebrew/Cellar/go/1.21.0/libexec/src/runtime/proc.go:310 +0x24

goroutine 18 [GC sweep wait]:
runtime.gopark(0x0?, 0x0?, 0x0?, 0x0?, 0x0?)
	/opt/homebrew/Cellar/go/1.21.0/libexec/src/runtime/proc.go:398 +0xc8 fp=0x14000044760 sp=0x14000044740 pc=0x1042794c8
runtime.goparkunlock(...)
	/opt/homebrew/Cellar/go/1.21.0/libexec/src/runtime/proc.go:404
runtime.bgsweep(0x0?)
	/opt/homebrew/Cellar/go/1.21.0/libexec/src/runtime/mgcsweep.go:280 +0xa0 fp=0x140000447b0 sp=0x14000044760 pc=0x104265cb0
runtime.gcenable.func1()
	/opt/homebrew/Cellar/go/1.21.0/libexec/src/runtime/mgc.go:200 +0x28 fp=0x140000447d0 sp=0x140000447b0 pc=0x10425aa08
runtime.goexit()
	/opt/homebrew/Cellar/go/1.21.0/libexec/src/runtime/asm_arm64.s:1197 +0x4 fp=0x140000447d0 sp=0x140000447d0 pc=0x1042a4484
created by runtime.gcenable in goroutine 1
	/opt/homebrew/Cellar/go/1.21.0/libexec/src/runtime/mgc.go:200 +0x6c

goroutine 19 [GC scavenge wait]:
runtime.gopark(0x1400008e000?, 0x104422460?, 0x1?, 0x0?, 0x140000824e0?)
	/opt/homebrew/Cellar/go/1.21.0/libexec/src/runtime/proc.go:398 +0xc8 fp=0x14000044f50 sp=0x14000044f30 pc=0x1042794c8
runtime.goparkunlock(...)
	/opt/homebrew/Cellar/go/1.21.0/libexec/src/runtime/proc.go:404
runtime.(*scavengerState).park(0x1044ec380)
	/opt/homebrew/Cellar/go/1.21.0/libexec/src/runtime/mgcscavenge.go:425 +0x5c fp=0x14000044f80 sp=0x14000044f50 pc=0x10426351c
runtime.bgscavenge(0x0?)
	/opt/homebrew/Cellar/go/1.21.0/libexec/src/runtime/mgcscavenge.go:653 +0x44 fp=0x14000044fb0 sp=0x14000044f80 pc=0x104263a74
runtime.gcenable.func2()
	/opt/homebrew/Cellar/go/1.21.0/libexec/src/runtime/mgc.go:201 +0x28 fp=0x14000044fd0 sp=0x14000044fb0 pc=0x10425a9a8
runtime.goexit()
	/opt/homebrew/Cellar/go/1.21.0/libexec/src/runtime/asm_arm64.s:1197 +0x4 fp=0x14000044fd0 sp=0x14000044fd0 pc=0x1042a4484
created by runtime.gcenable in goroutine 1
	/opt/homebrew/Cellar/go/1.21.0/libexec/src/runtime/mgc.go:201 +0xac

goroutine 34 [finalizer wait]:
runtime.gopark(0x27?, 0x0?, 0xe8?, 0x85?, 0x1042b8dac?)
	/opt/homebrew/Cellar/go/1.21.0/libexec/src/runtime/proc.go:398 +0xc8 fp=0x14000048580 sp=0x14000048560 pc=0x1042794c8
runtime.runfinq()
	/opt/homebrew/Cellar/go/1.21.0/libexec/src/runtime/mfinal.go:193 +0x108 fp=0x140000487d0 sp=0x14000048580 pc=0x104259af8
runtime.goexit()
	/opt/homebrew/Cellar/go/1.21.0/libexec/src/runtime/asm_arm64.s:1197 +0x4 fp=0x140000487d0 sp=0x140000487d0 pc=0x1042a4484
created by runtime.createfing in goroutine 1
	/opt/homebrew/Cellar/go/1.21.0/libexec/src/runtime/mfinal.go:163 +0x80

r0      0x164734000
r1      0x14000400000
r2      0x80
r3      0x1647342c0
r4      0x13e9bccbd40
r5      0x20
r6      0x600000e15950
r7      0xe
r8      0x5
r9      0x0
r10     0x12d6742f0
r11     0xffffffff
r12     0x1
r13     0xfffffd95
r14     0x7fb
r15     0xb2b357fb
r16     0x183849650
r17     0x23b94af40
r18     0x0
r19     0x178008000
r20     0x360
r21     0x140003ffd40
r22     0x88e4
r23     0x8892
r24     0x12d6741b0
r25     0x12d6741d8
r26     0x12d674238
r27     0x1780125a8
r28     0x1044ec420
r29     0x16bbbac00
lr      0x1ec130010
sp      0x16bbbabb0
pc      0x18384970c
fault   0x14000400000
exit status 2
```

**Comment by Dima-Kevanishvili** [comment]
🤦 After spending many hours trying to work this out, i saw that the VertexCount is wrong and after correcting it I no longer get crashes. 
Closing
