### ISSUE TITLE
opengl es

### ISSUE THREAD

**Issue by draeron** [gen2brain/raylib-go#88]
I tried running the examples on a raspberry pi / dietpi and I wasn't able to make it work. Note that i have compiled the raylib examples in C and they work, so it's not an external weird setup. Also i'm trying to run in without the X11 server.

this is the output i get :

```
mage_drawing: external/stb_image_resize.h:1064: stbir__calculate_coefficients_upsample: Assertion `stbir__filter_info_table[filter].kernel((float)(in_last_pixel + 1) + 0.5f - in_center_of_out, 1/scale) == 0' failed.
SIGABRT: abort
PC=0x76cf5f24 m=0 sigcode=4294967290
signal arrived during cgo execution

goroutine 1 [syscall, locked to thread]:
runtime.cgocall(0xaeccc, 0x182a71c, 0xaec28)
        /usr/local/go/src/runtime/cgocall.go:128 +0x5c fp=0x182a704 sp=0x182a6ec pc=0x27118
github.com/gen2brain/raylib-go/raylib._Cfunc_ImageResize(0x18840e0, 0x96, 0xc8)
        _cgo_gotypes.go:3001 +0x30 fp=0x182a718 sp=0x182a704 pc=0x99a04
github.com/gen2brain/raylib-go/raylib.ImageResize.func1(0x18840e0, 0x96, 0xc8)
        /home/pi/go/src/github.com/gen2brain/raylib-go/raylib/textures.go:249 +0x54 fp=0x182a730 sp=0x182a718 pc=0x9a86c
github.com/gen2brain/raylib-go/raylib.ImageResize(0x18840e0, 0x96, 0xc8)
        /home/pi/go/src/github.com/gen2brain/raylib-go/raylib/textures.go:249 +0x2c fp=0x182a740 sp=0x182a730 pc=0x9a2dc
main.main()
        /home/pi/go/src/github.com/gen2brain/raylib-go/examples/textures/image_drawing/main.go:17 +0xb0 fp=0x182a7a4 sp=0x182a740 pc=0x9b6ac
runtime.main()
        /usr/local/go/src/runtime/proc.go:203 +0x208 fp=0x182a7e4 sp=0x182a7a4 pc=0x502b8
runtime.goexit()
        /usr/local/go/src/runtime/asm_arm.s:868 +0x4 fp=0x182a7e4 sp=0x182a7e4 pc=0x77940

trap    0x0
error   0x0
oldmask 0x0
r0      0x0
r1      0x7ec1cfbc
r2      0x0
r3      0x8
r4      0x76ff9968
r5      0x6
r6      0x7ec1cfbc
r7      0xaf
r8      0x428
r9      0x1572f4
r10     0x0
fp      0x1497290
ip      0x0
sp      0x7ec1cfb8
lr      0xffffffff
pc      0x76cf5f24
cpsr    0x10
fault   0x0
```

**Comment by gen2brain** [comment]
Does this happen with all examples or specific ones?
It looks like some problem in stb_image_resize library, and also it looks like it is fixed in the newer version. I will try to update C libs these days, don't have time to add new functions right now, but the update can be done.

**Comment by draeron** [comment]
ok tested again and i didn't get the same result (it worked). Not sure what changed on my rpi meanwhile.

Also i've learned that to use glES on a raspberrypi require to disable _vc4_ hardware drivers but that give you a `* failed to add service - already in use?` message.

So i'll close this issue, sorry.
